### ISSUE TITLE
panic: eof while scanning long comment

### ISSUE THREAD

**Issue by wehimwich** [dehorsley/unlongify#1]
Carlo Migoni (Sardina) reports:

```
prog@fssr:~/go/bin$ ./unlongify /usr2/st/
panic: eof while scanning long comment

goroutine 35 [running]:
panic(0x810a060, 0x184203c8)
    /usr/lib/go-1.7/src/runtime/panic.go:500 +0x331
main.lexLongComment(0x18713320, 0x812e648)
    /usr2/prog/go/src/github.com/dehorsley/unlongify/scanner.go:149 +0x1a3
main.(*lexer).run(0x18713320)
    /usr2/prog/go/src/github.com/dehorsley/unlongify/scanner.go:80 +0x2d
created by main.lex
    /usr2/prog/go/src/github.com/dehorsley/unlongify/scanner.go:72 +0xac
```

Presumably there is an unterminated long comment at the end of a source file somewhere.  :) Maybe the compiler tolerates that, so it wasn't discovered before. If so, could/should _unlongify_ also tolerate it?

I'm waiting to get the file to check it. In the meantime they did the conversion by hand, so it isn't urgent. Would it would be easy to add the name of the offending file to error messages?

**Comment by dehorsley** [comment]
hmm when given a file with an open long comment, gcc fails with `error: unterminated comment` on my machine. It may be that the file that was causing the error isn't actually built; unlongify is just looking for every `*.c` and `*.h` file not actually what's in the Makefiles. Not sure what to do there then.

But a more useful error would certainly be a good start!

**Comment by wehimwich** [comment]
Carlo confirmed there was a *.c with the problem. Thanks for the error message.
